### ISSUE TITLE
distributor and availability in level-2

### ISSUE THREAD

**Issue by TomazErjavec** [COST-ELTeC/Schemas#2]
Level-1 allows distributor and availability (and they are used in SLV level-1) but leve-2 doesn't. They should be allowed with both (preferable, as level-1 has already been published), or disallowed in both.

**Comment by TomazErjavec** [comment]
It actually seems  a bit worse: level-1 requires these elements, while level-2 forbids them.

**Comment by lb42** [comment]
Apologies for this oversight. Now fixed, I think. Please test and close this ticket if it works!

**Comment by TomazErjavec** [comment]
OK now, thanks!
